# Generated by Django 4.2 on 2023-12-07 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymentnotification_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentnotification',
            options={'ordering': ['-id']},
        ),
    ]
