# Generated by Django 4.2 on 2023-11-07 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_slug'),
        ('webinar', '0002_alter_webinar_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='certificate',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.video'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='webinar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webinar.webinar'),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('user', 'webinar', 'video')},
        ),
    ]
