# Generated by Django 4.2 on 2023-10-23 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.JSONField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnail/')),
                ('date', models.DateTimeField()),
                ('instructor', models.CharField(max_length=100)),
                ('instructor_image', models.ImageField(blank=True, null=True, upload_to='videos/instructor/')),
                ('participants', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos/records/')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
        ),
    ]
