# Generated by Django 4.2 on 2023-06-29 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.JSONField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnail')),
                ('date', models.DateTimeField()),
                ('instructor', models.CharField(max_length=100)),
                ('instructor_image', models.ImageField(blank=True, null=True, upload_to='webinars/instructor/')),
                ('participants', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
