# Generated by Django 4.2 on 2023-08-04 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='video.video'),
        ),
    ]
