# Generated by Django 4.2 on 2023-10-23 22:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.JSONField()),
                ('source_certificate', models.FileField(blank=True, null=True, upload_to='webinars/source_certificates/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='webinars/main/')),
                ('date', models.DateTimeField()),
                ('instructor', models.CharField(max_length=100)),
                ('instructor_image', models.ImageField(blank=True, null=True, upload_to='webinars/instructor/')),
                ('certificates_added', models.BooleanField(default=False)),
                ('wp_group_url', models.URLField(max_length=400)),
                ('slug', models.SlugField(unique=True)),
                ('participants', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
