# Generated by Django 4.2 on 2023-07-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0002_alter_webinar_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='certificates_added',
            field=models.BooleanField(default=False),
        ),
    ]
